## This configuration was generated by terraform-provider-oci

resource oci_artifacts_container_configuration export_container_configuration {
  compartment_id                      = "ocid1.compartment.oc1..aaaaaaaa3zyzigwkufs5e4zks5rwtm244luxr5ztlj3ll6oznvh4dthydxnq"
  is_repository_created_on_first_push = "false"
}

resource oci_artifacts_container_repository export_wilbur-devops-app-demo-image {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T06:21:25.991Z"
  }
  display_name = "wilbur/devops/app-demo-image"
  freeform_tags = {
  }
  is_immutable = "false"
  is_public    = "true"
}

resource oci_artifacts_repository export_demo-app-artifact-repository {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-20T14:16:26.683Z"
  }
  description  = ""
  display_name = "demo-app-artifact-repository"
  freeform_tags = {
  }
  is_immutable    = "false"
  repository_type = "GENERIC"
}

resource oci_artifacts_generic_artifact export_app-sql-zip-1-0-0 {
  artifact_id = "ocid1.genericartifact.oc1.iad.0.amaaaaaaak7gbriaxulpglovi6wc5rmfajipuudag6w4de5yz5c4xc4gxlyq"
  defined_tags = {
    "default_tags.CreatedBy" = oci_devops_build_pipeline.export_build-demo-app.id
    "default_tags.CreatedOn" = "2025-09-24T00:49:43.401Z"
  }
  freeform_tags = {
  }
}

resource oci_artifacts_generic_artifact export_demo-app-yaml-1-0-0 {
  artifact_id = "ocid1.genericartifact.oc1.iad.0.amaaaaaaak7gbriafnx7n45jizy3z4ss35wf76dfi5pgffkue7k4btirm2aq"
  defined_tags = {
    "default_tags.CreatedBy" = oci_devops_build_pipeline.export_build-demo-app.id
    "default_tags.CreatedOn" = "2025-09-24T00:49:43.401Z"
  }
  freeform_tags = {
  }
}

