## This configuration was generated by terraform-provider-oci

resource oci_artifacts_container_configuration export_container_configuration {
  compartment_id                      = "ocid1.compartment.oc1..aaaaaaaa3zyzigwkufs5e4zks5rwtm244luxr5ztlj3ll6oznvh4dthydxnq"
  is_repository_created_on_first_push = "false"
}

resource oci_artifacts_repository export_demo-app-artifact-repository {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-20T14:16:26.683Z"
  }
  description  = ""
  display_name = "demo-app-artifact-repository"
  freeform_tags = {
  }
  is_immutable    = "false"
  repository_type = "GENERIC"
}

