## This configuration was generated by terraform-provider-oci

resource oci_containerengine_cluster export_OKE-Demo {
  cluster_pod_network_options {
    cni_type = "OCI_VCN_IP_NATIVE"
  }
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-19T08:19:24.723Z"
  }
  endpoint_config {
    is_public_ip_enabled = "true"
    nsg_ids = [
    ]
    subnet_id = oci_core_subnet.export_oke-api-subnet.id
  }
  freeform_tags = {
    "OKEclusterName" = "OKE-Demo"
  }
  image_policy_config {
    is_policy_enabled = "false"
  }
  #kms_key_id = <<Optional value not found in discovery>>
  kubernetes_version = "v1.33.1"
  name               = "OKE-Demo"
  options {
    add_ons {
      is_kubernetes_dashboard_enabled = "false"
      is_tiller_enabled               = "false"
    }
    admission_controller_options {
      is_pod_security_policy_enabled = "false"
    }
    ip_families = [
      "IPv4",
    ]
    kubernetes_network_config {
      pods_cidr     = "10.244.0.0/16"
      services_cidr = "10.96.0.0/16"
    }
    #open_id_connect_discovery = <<Optional value not found in discovery>>
    #open_id_connect_token_authentication_config = <<Optional value not found in discovery>>
    persistent_volume_config {
      defined_tags = {
      }
      freeform_tags = {
        "OKEclusterName" = "OKE-Demo"
      }
    }
    service_lb_config {
      defined_tags = {
      }
      freeform_tags = {
        "OKEclusterName" = "OKE-Demo"
      }
    }
    service_lb_subnet_ids = [
      oci_core_subnet.export_oke-svclb-subnet.id,
    ]
  }
  type   = "ENHANCED_CLUSTER"
  vcn_id = oci_core_vcn.export_oke-vcn-quick-OKE-Demo-2e4514f35.id
}

resource oci_containerengine_node_pool export_pool1 {
  cluster_id     = oci_containerengine_cluster.export_OKE-Demo.id
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-19T08:19:27.592Z"
  }
  freeform_tags = {
    "OKEnodePoolName" = "pool1"
  }
  initial_node_labels {
    key   = "name"
    value = "OKE-Demo"
  }
  kubernetes_version = "v1.33.1"
  name               = "pool1"
  node_config_details {
    defined_tags = {
    }
    freeform_tags = {
      "OKEnodePoolName" = "pool1"
    }
    #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    node_pool_pod_network_option_details {
      cni_type          = "OCI_VCN_IP_NATIVE"
      max_pods_per_node = "31"
      pod_nsg_ids = [
      ]
      pod_subnet_ids = [
        oci_core_subnet.export_oke-api-subnet.id,
      ]
    }
    nsg_ids = [
    ]
    placement_configs {
      availability_domain = data.oci_identity_availability_domain.export_bxtG-US-ASHBURN-AD-1.name
      #capacity_reservation_id = <<Optional value not found in discovery>>
      fault_domains = [
      ]
      #preemptible_node_config = <<Optional value not found in discovery>>
      subnet_id = oci_core_subnet.export_oke-api-subnet.id
    }
    size = "1"
  }
  node_eviction_node_pool_settings {
    eviction_grace_duration = "PT1H"
    #is_force_action_after_grace_duration = <<Optional value not found in discovery>>
    is_force_delete_after_grace_duration = "false"
  }
  node_metadata = {
  }
  node_shape = "VM.Standard.E5.Flex"
  node_shape_config {
    memory_in_gbs = "16"
    ocpus         = "1"
  }
  node_source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    image_id    = var.oci_core_instance--source_details-source_id--export_oke-cgnjnagsaqq-nooqmmoqf7a-s2sjo3cxluq-0_1
    source_type = "IMAGE"
  }
  #quantity_per_subnet = <<Optional value not found in discovery>>
  #ssh_public_key = <<Optional value not found in discovery>>
  #subnet_ids = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_OKE-Demo_addon {
  addon_name = "KubeProxy"
  cluster_id = oci_containerengine_cluster.export_OKE-Demo.id
  #override_existing = <<Optional value not found in discovery>>
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_OKE-Demo_addon_1 {
  addon_name = "NvidiaGpuPlugin"
  cluster_id = oci_containerengine_cluster.export_OKE-Demo.id
  #override_existing = <<Optional value not found in discovery>>
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_OKE-Demo_addon_2 {
  addon_name = "OciVcnIpNative"
  cluster_id = oci_containerengine_cluster.export_OKE-Demo.id
  #override_existing = <<Optional value not found in discovery>>
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

