## This configuration was generated by terraform-provider-oci

resource oci_containerengine_node_pool export_pool1 {
  cluster_id     = oci_containerengine_cluster.export_Demo-OKE-US.id
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T16:45:17.064Z"
  }
  freeform_tags = {
  }
  initial_node_labels {
    key   = "name"
    value = "pool1"
  }
  kubernetes_version = "v1.31.10"
  name               = "pool1"
  node_config_details {
    defined_tags = {
    }
    freeform_tags = {
    }
    is_pv_encryption_in_transit_enabled = "false"
    #kms_key_id = <<Optional value not found in discovery>>
    node_pool_pod_network_option_details {
      cni_type          = "OCI_VCN_IP_NATIVE"
      max_pods_per_node = "31"
      pod_nsg_ids = [
      ]
      pod_subnet_ids = [
        oci_core_subnet.export_private-subnet.id,
      ]
    }
    nsg_ids = [
    ]
    placement_configs {
      availability_domain = data.oci_identity_availability_domain.export_bxtG-US-ASHBURN-AD-1.name
      #capacity_reservation_id = <<Optional value not found in discovery>>
      fault_domains = [
        "FAULT-DOMAIN-1",
        "FAULT-DOMAIN-2",
        "FAULT-DOMAIN-3",
      ]
      #preemptible_node_config = <<Optional value not found in discovery>>
      subnet_id = oci_core_subnet.export_private-subnet.id
    }
    size = "1"
  }
  node_eviction_node_pool_settings {
    eviction_grace_duration = "PT1H"
    #is_force_action_after_grace_duration = <<Optional value not found in discovery>>
    is_force_delete_after_grace_duration = "false"
  }
  node_metadata = {
  }
  node_shape = "VM.Standard.E3.Flex"
  node_shape_config {
    memory_in_gbs = "16"
    ocpus         = "1"
  }
  node_source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    image_id    = var.oci_core_instance--source_details-source_id--export_oke-crfols6nacq-n7v5y6wfi6a-s56tjf5wxja-0_1
    source_type = "IMAGE"
  }
  #quantity_per_subnet = <<Optional value not found in discovery>>
  ssh_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA7FmSPqmQxQDnMpbEF1NApFKZNHJ/LNyIwGUgy5gUnN3ZrTotiS4z+H6F8uGrKxn4nBhbezqgMq2/Hva4LIGAqFyLEkyqUxzvwihAqEv4Jamf/M9ed6gjnIjm1WJF6qfMLDN24mEG3i2YHEUgFoOYetCqyDVijWgQcF0j/IpAmhwJkftnKFLJXs1Lmeg3F9D2rAY4Y5iNGcJzxOH+/XT2L/4o+XqE88WBzt5DGWUpPBzdsj770Er2X6Gdmp9USFFYyFMM7/YpPg8qUnXpApyUz6NO//a37c22M7AkSaX4g5kMevgdxFqYaiWF4eNWx1eC+4/jak+x5qV0BIEymmrl wilbur\n"
  #subnet_ids = <<Optional value not found in discovery>>
}

resource oci_containerengine_cluster export_Demo-OKE-US {
  cluster_pod_network_options {
    cni_type = "OCI_VCN_IP_NATIVE"
  }
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T16:45:14.433Z"
  }
  endpoint_config {
    is_public_ip_enabled = "true"
    nsg_ids = [
    ]
    subnet_id = oci_core_subnet.export_oke-api-subnet.id
  }
  freeform_tags = {
  }
  image_policy_config {
    is_policy_enabled = "false"
  }
  #kms_key_id = <<Optional value not found in discovery>>
  kubernetes_version = "v1.31.10"
  name               = "Demo-OKE-US"
  options {
    add_ons {
      is_kubernetes_dashboard_enabled = "false"
      is_tiller_enabled               = "false"
    }
    admission_controller_options {
      is_pod_security_policy_enabled = "false"
    }
    ip_families = [
      "IPv4",
    ]
    kubernetes_network_config {
      pods_cidr     = "10.244.0.0/16"
      services_cidr = "10.96.0.0/16"
    }
    #open_id_connect_discovery = <<Optional value not found in discovery>>
    #open_id_connect_token_authentication_config = <<Optional value not found in discovery>>
    persistent_volume_config {
      #defined_tags = <<Optional value not found in discovery>>
      freeform_tags = {
      }
    }
    service_lb_config {
      #defined_tags = <<Optional value not found in discovery>>
      freeform_tags = {
      }
    }
    service_lb_subnet_ids = [
    ]
  }
  type   = "ENHANCED_CLUSTER"
  vcn_id = oci_core_vcn.export_oke-vcn-quick-OKE-Demo-2e4514f35.id
}

resource oci_containerengine_addon export_Demo-OKE-US_addon {
  addon_name = "CoreDNS"
  cluster_id = oci_containerengine_cluster.export_Demo-OKE-US.id
  #override_existing = <<Optional value not found in discovery>>
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_Demo-OKE-US_addon_1 {
  addon_name = "KubeProxy"
  cluster_id = oci_containerengine_cluster.export_Demo-OKE-US.id
  #override_existing = <<Optional value not found in discovery>>
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_Demo-OKE-US_addon_2 {
  addon_name = "NvidiaGpuPlugin"
  cluster_id = oci_containerengine_cluster.export_Demo-OKE-US.id
  #override_existing = <<Optional value not found in discovery>>
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

resource oci_containerengine_addon export_Demo-OKE-US_addon_3 {
  addon_name = "OciVcnIpNative"
  cluster_id = oci_containerengine_cluster.export_Demo-OKE-US.id
  #override_existing = <<Optional value not found in discovery>>
  remove_addon_resources_on_delete = "true"
  #version = <<Optional value not found in discovery>>
}

