## This configuration was generated by terraform-provider-oci

resource oci_devops_repository export_app-demo {
  default_branch = "refs/heads/main"
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-19T08:44:13.899Z"
  }
  description = ""
  freeform_tags = {
  }
  name                 = "app-demo"
  parent_repository_id = ""
  project_id           = oci_devops_project.export_DevOps-Demo.id
  repository_type      = "HOSTED"
}

resource oci_devops_project export_DevOps-Demo {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-19T08:42:43.441Z"
  }
  description = "A Devops project for OKE and ADB"
  freeform_tags = {
  }
  name = "DevOps-Demo"
  notification_config {
    topic_id = oci_ons_notification_topic.export_Topic-Demo.id
  }
}

resource oci_devops_deploy_environment export_Demo-OKE-US-env {
  cluster_id = oci_containerengine_cluster.export_Demo-OKE-US.id
  #compute_instance_group_selectors = <<Optional value not found in discovery>>
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-20T14:01:33.742Z"
  }
  deploy_environment_type = "OKE_CLUSTER"
  description             = ""
  display_name            = "Demo-OKE-US-env"
  freeform_tags = {
  }
  #function_id = <<Optional value not found in discovery>>
  project_id = oci_devops_project.export_DevOps-Demo.id
}

resource oci_devops_deploy_pipeline export_Deploy-OKE-ADB-US {
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T12:08:00.176Z"
  }
  deploy_pipeline_parameters {
    items {
      default_value = "1.0.0"
      description   = ""
      name          = "APP_VERSION"
    }
  }
  description  = ""
  display_name = "Deploy-OKE-ADB-US"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_DevOps-Demo.id
}

resource oci_devops_deploy_pipeline export_Deploy-OKE-ADB-SG {
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-20T14:06:57.716Z"
  }
  deploy_pipeline_parameters {
    items {
      default_value = "1.0.0"
      description   = ""
      name          = "APP_VERSION"
    }
  }
  description  = ""
  display_name = "Deploy-OKE-ADB-SG"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_DevOps-Demo.id
}

resource oci_devops_project_repository_setting export_DevOps-Demo_project_repository_setting {
  approval_rules {
  }
  merge_settings {
    allowed_merge_strategies = [
      "MERGE_COMMIT",
    ]
    default_merge_strategy = "MERGE_COMMIT"
  }
  project_id = oci_devops_project.export_DevOps-Demo.id
}

resource oci_devops_deploy_stage export_Deploy-app-to-OKE {
  #approval_policy = <<Optional value not found in discovery>>
  #are_hooks_enabled = <<Optional value not found in discovery>>
  #blue_backend_ips = <<Optional value not found in discovery>>
  #blue_green_strategy = <<Optional value not found in discovery>>
  #canary_strategy = <<Optional value not found in discovery>>
  #command_spec_deploy_artifact_id = <<Optional value not found in discovery>>
  #compute_instance_group_blue_green_deployment_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_deploy_environment_id = <<Optional value not found in discovery>>
  #config = <<Optional value not found in discovery>>
  #container_config = <<Optional value not found in discovery>>
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T15:11:23.401Z"
  }
  #deploy_artifact_id = <<Optional value not found in discovery>>
  #deploy_artifact_ids = <<Optional value not found in discovery>>
  #deploy_environment_id_a = <<Optional value not found in discovery>>
  #deploy_environment_id_b = <<Optional value not found in discovery>>
  deploy_pipeline_id = oci_devops_deploy_pipeline.export_Deploy-OKE-ADB-US.id
  deploy_stage_predecessor_collection {
    items {
      id = oci_devops_deploy_stage.export_Apply-SQL.id
    }
  }
  deploy_stage_type = "OKE_DEPLOYMENT"
  #deployment_spec_deploy_artifact_id = <<Optional value not found in discovery>>
  description  = ""
  display_name = "Deploy app to OKE"
  #docker_image_deploy_artifact_id = <<Optional value not found in discovery>>
  #failure_policy = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #function_deploy_environment_id = <<Optional value not found in discovery>>
  #function_timeout_in_seconds = <<Optional value not found in discovery>>
  #green_backend_ips = <<Optional value not found in discovery>>
  #helm_chart_deploy_artifact_id = <<Optional value not found in discovery>>
  #helm_command_artifact_ids = <<Optional value not found in discovery>>
  #is_async = <<Optional value not found in discovery>>
  #is_debug_enabled = <<Optional value not found in discovery>>
  #is_force_enabled = <<Optional value not found in discovery>>
  #is_uninstall_on_stage_delete = <<Optional value not found in discovery>>
  #is_validation_enabled = <<Optional value not found in discovery>>
  kubernetes_manifest_deploy_artifact_ids = [
    oci_devops_deploy_artifact.export_app-domo-manifest.id,
  ]
  #load_balancer_config = <<Optional value not found in discovery>>
  #max_history = <<Optional value not found in discovery>>
  #max_memory_in_mbs = <<Optional value not found in discovery>>
  namespace = "default"
  #oke_blue_green_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  oke_cluster_deploy_environment_id = oci_devops_deploy_environment.export_Demo-OKE-US-env.id
  #production_load_balancer_config = <<Optional value not found in discovery>>
  #purpose = <<Optional value not found in discovery>>
  #release_name = <<Optional value not found in discovery>>
  rollback_policy {
    policy_type = "NO_STAGE_ROLLBACK_POLICY"
  }
  #rollout_policy = <<Optional value not found in discovery>>
  #set_string = <<Optional value not found in discovery>>
  #set_values = <<Optional value not found in discovery>>
  #should_cleanup_on_fail = <<Optional value not found in discovery>>
  #should_not_wait = <<Optional value not found in discovery>>
  #should_reset_values = <<Optional value not found in discovery>>
  #should_reuse_values = <<Optional value not found in discovery>>
  #should_skip_crds = <<Optional value not found in discovery>>
  #should_skip_render_subchart_notes = <<Optional value not found in discovery>>
  #test_load_balancer_config = <<Optional value not found in discovery>>
  #timeout_in_seconds = <<Optional value not found in discovery>>
  #traffic_shift_target = <<Optional value not found in discovery>>
  #values_artifact_ids = <<Optional value not found in discovery>>
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_deploy_stage export_Apply-SQL {
  #approval_policy = <<Optional value not found in discovery>>
  #are_hooks_enabled = <<Optional value not found in discovery>>
  #blue_backend_ips = <<Optional value not found in discovery>>
  #blue_green_strategy = <<Optional value not found in discovery>>
  #canary_strategy = <<Optional value not found in discovery>>
  command_spec_deploy_artifact_id = oci_devops_deploy_artifact.export_run_shell.id
  #compute_instance_group_blue_green_deployment_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_deploy_environment_id = <<Optional value not found in discovery>>
  #config = <<Optional value not found in discovery>>
  container_config {
    availability_domain   = data.oci_identity_availability_domain.export_bxtG-US-ASHBURN-AD-1.name
    compartment_id        = oci_artifacts_container_configuration.export_container_configuration.id
    container_config_type = "CONTAINER_INSTANCE_CONFIG"
    network_channel {
      network_channel_type = "SERVICE_VNIC_CHANNEL"
      nsg_ids = [
      ]
      subnet_id = oci_core_subnet.export_private-subnet.id
    }
    shape_config {
      memory_in_gbs = "4"
      ocpus         = "2"
    }
    shape_name = "CI.Standard.E4.Flex"
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T12:08:35.313Z"
  }
  #deploy_artifact_id = <<Optional value not found in discovery>>
  #deploy_artifact_ids = <<Optional value not found in discovery>>
  #deploy_environment_id_a = <<Optional value not found in discovery>>
  #deploy_environment_id_b = <<Optional value not found in discovery>>
  deploy_pipeline_id = oci_devops_deploy_pipeline.export_Deploy-OKE-ADB-US.id
  deploy_stage_predecessor_collection {
    items {
      id = oci_devops_deploy_pipeline.export_Deploy-OKE-ADB-US.id
    }
  }
  deploy_stage_type = "SHELL"
  #deployment_spec_deploy_artifact_id = <<Optional value not found in discovery>>
  description  = ""
  display_name = "Apply SQL"
  #docker_image_deploy_artifact_id = <<Optional value not found in discovery>>
  #failure_policy = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #function_deploy_environment_id = <<Optional value not found in discovery>>
  #function_timeout_in_seconds = <<Optional value not found in discovery>>
  #green_backend_ips = <<Optional value not found in discovery>>
  #helm_chart_deploy_artifact_id = <<Optional value not found in discovery>>
  #helm_command_artifact_ids = <<Optional value not found in discovery>>
  #is_async = <<Optional value not found in discovery>>
  #is_debug_enabled = <<Optional value not found in discovery>>
  #is_force_enabled = <<Optional value not found in discovery>>
  #is_uninstall_on_stage_delete = <<Optional value not found in discovery>>
  #is_validation_enabled = <<Optional value not found in discovery>>
  #kubernetes_manifest_deploy_artifact_ids = <<Optional value not found in discovery>>
  #load_balancer_config = <<Optional value not found in discovery>>
  #max_history = <<Optional value not found in discovery>>
  #max_memory_in_mbs = <<Optional value not found in discovery>>
  #namespace = <<Optional value not found in discovery>>
  #oke_blue_green_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_cluster_deploy_environment_id = <<Optional value not found in discovery>>
  #production_load_balancer_config = <<Optional value not found in discovery>>
  #purpose = <<Optional value not found in discovery>>
  #release_name = <<Optional value not found in discovery>>
  #rollback_policy = <<Optional value not found in discovery>>
  #rollout_policy = <<Optional value not found in discovery>>
  #set_string = <<Optional value not found in discovery>>
  #set_values = <<Optional value not found in discovery>>
  #should_cleanup_on_fail = <<Optional value not found in discovery>>
  #should_not_wait = <<Optional value not found in discovery>>
  #should_reset_values = <<Optional value not found in discovery>>
  #should_reuse_values = <<Optional value not found in discovery>>
  #should_skip_crds = <<Optional value not found in discovery>>
  #should_skip_render_subchart_notes = <<Optional value not found in discovery>>
  #test_load_balancer_config = <<Optional value not found in discovery>>
  timeout_in_seconds = "36000"
  #traffic_shift_target = <<Optional value not found in discovery>>
  #values_artifact_ids = <<Optional value not found in discovery>>
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_deploy_stage export_Apply-SQL_1 {
  #approval_policy = <<Optional value not found in discovery>>
  #are_hooks_enabled = <<Optional value not found in discovery>>
  #blue_backend_ips = <<Optional value not found in discovery>>
  #blue_green_strategy = <<Optional value not found in discovery>>
  #canary_strategy = <<Optional value not found in discovery>>
  command_spec_deploy_artifact_id = oci_devops_deploy_artifact.export_run_shell.id
  #compute_instance_group_blue_green_deployment_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_deploy_environment_id = <<Optional value not found in discovery>>
  #config = <<Optional value not found in discovery>>
  container_config {
    availability_domain   = data.oci_identity_availability_domain.export_bxtG-US-ASHBURN-AD-1.name
    compartment_id        = oci_artifacts_container_configuration.export_container_configuration.id
    container_config_type = "CONTAINER_INSTANCE_CONFIG"
    network_channel {
      network_channel_type = "SERVICE_VNIC_CHANNEL"
      nsg_ids = [
      ]
      subnet_id = oci_core_subnet.export_private-subnet.id
    }
    shape_config {
      memory_in_gbs = "4"
      ocpus         = "2"
    }
    shape_name = "CI.Standard.E4.Flex"
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-21T05:40:02.151Z"
  }
  #deploy_artifact_id = <<Optional value not found in discovery>>
  #deploy_artifact_ids = <<Optional value not found in discovery>>
  #deploy_environment_id_a = <<Optional value not found in discovery>>
  #deploy_environment_id_b = <<Optional value not found in discovery>>
  deploy_pipeline_id = oci_devops_deploy_pipeline.export_Deploy-OKE-ADB-SG.id
  deploy_stage_predecessor_collection {
    items {
      id = oci_devops_deploy_pipeline.export_Deploy-OKE-ADB-SG.id
    }
  }
  deploy_stage_type = "SHELL"
  #deployment_spec_deploy_artifact_id = <<Optional value not found in discovery>>
  description  = ""
  display_name = "Apply SQL"
  #docker_image_deploy_artifact_id = <<Optional value not found in discovery>>
  #failure_policy = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #function_deploy_environment_id = <<Optional value not found in discovery>>
  #function_timeout_in_seconds = <<Optional value not found in discovery>>
  #green_backend_ips = <<Optional value not found in discovery>>
  #helm_chart_deploy_artifact_id = <<Optional value not found in discovery>>
  #helm_command_artifact_ids = <<Optional value not found in discovery>>
  #is_async = <<Optional value not found in discovery>>
  #is_debug_enabled = <<Optional value not found in discovery>>
  #is_force_enabled = <<Optional value not found in discovery>>
  #is_uninstall_on_stage_delete = <<Optional value not found in discovery>>
  #is_validation_enabled = <<Optional value not found in discovery>>
  #kubernetes_manifest_deploy_artifact_ids = <<Optional value not found in discovery>>
  #load_balancer_config = <<Optional value not found in discovery>>
  #max_history = <<Optional value not found in discovery>>
  #max_memory_in_mbs = <<Optional value not found in discovery>>
  #namespace = <<Optional value not found in discovery>>
  #oke_blue_green_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_cluster_deploy_environment_id = <<Optional value not found in discovery>>
  #production_load_balancer_config = <<Optional value not found in discovery>>
  #purpose = <<Optional value not found in discovery>>
  #release_name = <<Optional value not found in discovery>>
  #rollback_policy = <<Optional value not found in discovery>>
  #rollout_policy = <<Optional value not found in discovery>>
  #set_string = <<Optional value not found in discovery>>
  #set_values = <<Optional value not found in discovery>>
  #should_cleanup_on_fail = <<Optional value not found in discovery>>
  #should_not_wait = <<Optional value not found in discovery>>
  #should_reset_values = <<Optional value not found in discovery>>
  #should_reuse_values = <<Optional value not found in discovery>>
  #should_skip_crds = <<Optional value not found in discovery>>
  #should_skip_render_subchart_notes = <<Optional value not found in discovery>>
  #test_load_balancer_config = <<Optional value not found in discovery>>
  timeout_in_seconds = "420"
  #traffic_shift_target = <<Optional value not found in discovery>>
  #values_artifact_ids = <<Optional value not found in discovery>>
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_deploy_stage export_deploy-demo-app-to-OKE {
  #approval_policy = <<Optional value not found in discovery>>
  #are_hooks_enabled = <<Optional value not found in discovery>>
  #blue_backend_ips = <<Optional value not found in discovery>>
  #blue_green_strategy = <<Optional value not found in discovery>>
  #canary_strategy = <<Optional value not found in discovery>>
  #command_spec_deploy_artifact_id = <<Optional value not found in discovery>>
  #compute_instance_group_blue_green_deployment_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_deploy_environment_id = <<Optional value not found in discovery>>
  #config = <<Optional value not found in discovery>>
  #container_config = <<Optional value not found in discovery>>
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-20T14:20:43.847Z"
  }
  #deploy_artifact_id = <<Optional value not found in discovery>>
  #deploy_artifact_ids = <<Optional value not found in discovery>>
  #deploy_environment_id_a = <<Optional value not found in discovery>>
  #deploy_environment_id_b = <<Optional value not found in discovery>>
  deploy_pipeline_id = oci_devops_deploy_pipeline.export_Deploy-OKE-ADB-SG.id
  deploy_stage_predecessor_collection {
    items {
      id = oci_devops_deploy_stage.export_Apply-SQL_1.id
    }
  }
  deploy_stage_type = "OKE_DEPLOYMENT"
  #deployment_spec_deploy_artifact_id = <<Optional value not found in discovery>>
  description  = ""
  display_name = "deploy  demo app to OKE"
  #docker_image_deploy_artifact_id = <<Optional value not found in discovery>>
  #failure_policy = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #function_deploy_environment_id = <<Optional value not found in discovery>>
  #function_timeout_in_seconds = <<Optional value not found in discovery>>
  #green_backend_ips = <<Optional value not found in discovery>>
  #helm_chart_deploy_artifact_id = <<Optional value not found in discovery>>
  #helm_command_artifact_ids = <<Optional value not found in discovery>>
  #is_async = <<Optional value not found in discovery>>
  #is_debug_enabled = <<Optional value not found in discovery>>
  #is_force_enabled = <<Optional value not found in discovery>>
  #is_uninstall_on_stage_delete = <<Optional value not found in discovery>>
  #is_validation_enabled = <<Optional value not found in discovery>>
  kubernetes_manifest_deploy_artifact_ids = [
    oci_devops_deploy_artifact.export_app-domo-manifest.id,
  ]
  #load_balancer_config = <<Optional value not found in discovery>>
  #max_history = <<Optional value not found in discovery>>
  #max_memory_in_mbs = <<Optional value not found in discovery>>
  namespace = "default"
  #oke_blue_green_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  oke_cluster_deploy_environment_id = oci_devops_deploy_environment.export_Demo-OKE-US-env.id
  #production_load_balancer_config = <<Optional value not found in discovery>>
  #purpose = <<Optional value not found in discovery>>
  #release_name = <<Optional value not found in discovery>>
  rollback_policy {
    policy_type = "NO_STAGE_ROLLBACK_POLICY"
  }
  #rollout_policy = <<Optional value not found in discovery>>
  #set_string = <<Optional value not found in discovery>>
  #set_values = <<Optional value not found in discovery>>
  #should_cleanup_on_fail = <<Optional value not found in discovery>>
  #should_not_wait = <<Optional value not found in discovery>>
  #should_reset_values = <<Optional value not found in discovery>>
  #should_reuse_values = <<Optional value not found in discovery>>
  #should_skip_crds = <<Optional value not found in discovery>>
  #should_skip_render_subchart_notes = <<Optional value not found in discovery>>
  #test_load_balancer_config = <<Optional value not found in discovery>>
  #timeout_in_seconds = <<Optional value not found in discovery>>
  #traffic_shift_target = <<Optional value not found in discovery>>
  #values_artifact_ids = <<Optional value not found in discovery>>
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_deploy_artifact export_run_shell {
  argument_substitution_mode = "SUBSTITUTE_PLACEHOLDERS"
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T12:07:31.422Z"
  }
  deploy_artifact_source {
    base64encoded_content = "version: 0.1\ncomponent: command\ntimeoutInSeconds: 3600\nshell: bash\nfailImmediatelyOnError: true\n\ninputArtifacts:\n  - name: \"app-demo-sql-zip\"\n    type: \"GENERIC_ARTIFACT\"\n    registryId: \"ocid1.artifactrepository.oc1.iad.0.amaaaaaaak7gbriaev2wihpkqknnbvvx2xm6oajzjf23kpzieoxt7gja2loa\"\n    path: \"app-sql.zip\"\n    version: \"$${APP_VERSION}\"\n    location:  \"app-sql.zip\"\n\nsteps:\n  - type: Command\n    name: \"Apply SQL 2\"\n    shell: bash\n    timeoutInSeconds: 300\n    failImmediatelyOnError: true\n    command: |\n      echo \"Apply SQL 6\"\n      which sql\n      sql -V\n      ls -lh\n      unzip app-sql.zip\n      ls\n      cat run-sql-command.sh\n      ./run-sql-command.sh"
    #chart_url = <<Optional value not found in discovery>>
    #deploy_artifact_path = <<Optional value not found in discovery>>
    deploy_artifact_source_type = "INLINE"
    #deploy_artifact_version = <<Optional value not found in discovery>>
    #helm_artifact_source_type = <<Optional value not found in discovery>>
    #helm_verification_key_source = <<Optional value not found in discovery>>
    #image_digest = <<Optional value not found in discovery>>
    #image_uri = <<Optional value not found in discovery>>
    #repository_id = <<Optional value not found in discovery>>
  }
  deploy_artifact_type = "COMMAND_SPEC"
  description          = ""
  display_name         = "run_shell"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_DevOps-Demo.id
}

resource oci_devops_deploy_artifact export_app-demo-sql-zip {
  argument_substitution_mode = "SUBSTITUTE_PLACEHOLDERS"
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T11:45:14.759Z"
  }
  deploy_artifact_source {
    #base64encoded_content = <<Optional value not found in discovery>>
    #chart_url = <<Optional value not found in discovery>>
    deploy_artifact_path        = "app-sql.zip"
    deploy_artifact_source_type = "GENERIC_ARTIFACT"
    deploy_artifact_version     = "$${APP_VERSION}"
    #helm_artifact_source_type = <<Optional value not found in discovery>>
    #helm_verification_key_source = <<Optional value not found in discovery>>
    #image_digest = <<Optional value not found in discovery>>
    #image_uri = <<Optional value not found in discovery>>
    repository_id = oci_artifacts_repository.export_demo-app-artifact-repository.id
  }
  deploy_artifact_type = "GENERIC_FILE"
  description          = ""
  display_name         = "app-demo-sql-zip"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_DevOps-Demo.id
}

resource oci_devops_deploy_artifact export_app-domo-manifest {
  argument_substitution_mode = "SUBSTITUTE_PLACEHOLDERS"
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-20T14:18:26.935Z"
  }
  deploy_artifact_source {
    #base64encoded_content = <<Optional value not found in discovery>>
    #chart_url = <<Optional value not found in discovery>>
    deploy_artifact_path        = "demo-app.yaml"
    deploy_artifact_source_type = "GENERIC_ARTIFACT"
    deploy_artifact_version     = "$${APP_VERSION}"
    #helm_artifact_source_type = <<Optional value not found in discovery>>
    #helm_verification_key_source = <<Optional value not found in discovery>>
    #image_digest = <<Optional value not found in discovery>>
    #image_uri = <<Optional value not found in discovery>>
    repository_id = oci_artifacts_repository.export_demo-app-artifact-repository.id
  }
  deploy_artifact_type = "KUBERNETES_MANIFEST"
  description          = ""
  display_name         = "app-domo-manifest"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_DevOps-Demo.id
}

resource oci_devops_deploy_artifact export_app-demo-image {
  argument_substitution_mode = "SUBSTITUTE_PLACEHOLDERS"
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-20T10:03:44.113Z"
  }
  deploy_artifact_source {
    #base64encoded_content = <<Optional value not found in discovery>>
    #chart_url = <<Optional value not found in discovery>>
    #deploy_artifact_path = <<Optional value not found in discovery>>
    deploy_artifact_source_type = "OCIR"
    #deploy_artifact_version = <<Optional value not found in discovery>>
    #helm_artifact_source_type = <<Optional value not found in discovery>>
    #helm_verification_key_source = <<Optional value not found in discovery>>
    image_digest = ""
    image_uri    = "iad.ocir.io/sehubjapacprod/wilbur/devops/app-demo-image:$${APP_VERSION}"
    #repository_id = <<Optional value not found in discovery>>
  }
  deploy_artifact_type = "DOCKER_IMAGE"
  description          = ""
  display_name         = "app-demo-image"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_DevOps-Demo.id
}

resource oci_devops_build_pipeline_stage export_deliver-artifacts {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_pipeline_stage_predecessor_collection {
    items {
      id = oci_devops_build_pipeline_stage.export_build-image.id
    }
  }
  build_pipeline_stage_type = "DELIVER_ARTIFACT"
  #build_runner_shape_config = <<Optional value not found in discovery>>
  #build_source_collection = <<Optional value not found in discovery>>
  #build_spec_file = <<Optional value not found in discovery>>
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-20T13:59:34.412Z"
  }
  deliver_artifact_collection {
    items {
      artifact_id   = oci_devops_deploy_artifact.export_app-demo-image.id
      artifact_name = "app-demo-image"
    }
    items {
      artifact_id   = oci_devops_deploy_artifact.export_app-domo-manifest.id
      artifact_name = "app-demo-manifest"
    }
    items {
      artifact_id   = oci_devops_deploy_artifact.export_app-demo-sql-zip.id
      artifact_name = "app-demo-sql-zip"
    }
  }
  #deploy_pipeline_id = <<Optional value not found in discovery>>
  description  = ""
  display_name = "deliver artifacts"
  freeform_tags = {
  }
  #image = <<Optional value not found in discovery>>
  #is_pass_all_parameters_enabled = <<Optional value not found in discovery>>
  #primary_build_source = <<Optional value not found in discovery>>
  #private_access_config = <<Optional value not found in discovery>>
  #stage_execution_timeout_in_seconds = <<Optional value not found in discovery>>
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_build_pipeline_stage export_build-image {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_pipeline_stage_predecessor_collection {
    items {
      id = oci_devops_build_pipeline.export_build-demo-app.id
    }
  }
  build_pipeline_stage_type = "BUILD"
  build_runner_shape_config {
    build_runner_type = "DEFAULT"
    #memory_in_gbs = <<Optional value not found in discovery>>
    #ocpus = <<Optional value not found in discovery>>
  }
  build_source_collection {
    items {
      branch = "main"
      #connection_id = <<Optional value not found in discovery>>
      connection_type = "DEVOPS_CODE_REPOSITORY"
      name            = "app-demo"
      repository_id   = oci_devops_repository.export_app-demo.id
      repository_url  = "https://devops.scmservice.us-ashburn-1.oci.oraclecloud.com/namespaces/sehubjapacprod/projects/DevOps-Demo/repositories/app-demo"
    }
  }
  build_spec_file = "build_spec.yaml"
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-19T08:51:42.316Z"
  }
  #deliver_artifact_collection = <<Optional value not found in discovery>>
  #deploy_pipeline_id = <<Optional value not found in discovery>>
  description  = ""
  display_name = "build image"
  freeform_tags = {
  }
  image = "OL8_X86_64_STANDARD_10"
  #is_pass_all_parameters_enabled = <<Optional value not found in discovery>>
  primary_build_source               = "app-demo"
  stage_execution_timeout_in_seconds = "600"
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_repository_ref export_app-demo_repository_ref {
  commit_id = "8ffbdbe6bcf9a99e31131417d164d76f1f81d71d"
  #object_id = <<Optional value not found in discovery>>
  ref_name      = "main"
  ref_type      = "BRANCH"
  repository_id = oci_devops_repository.export_app-demo.id
}

resource oci_devops_repository_setting export_app-demo_repository_setting {
  approval_rules {
  }
  merge_checks {
    last_build_succeeded = "DISABLED"
  }
  merge_settings {
    allowed_merge_strategies = [
      "MERGE_COMMIT",
    ]
    default_merge_strategy = "MERGE_COMMIT"
  }
  repository_id = oci_devops_repository.export_app-demo.id
}

resource oci_devops_build_pipeline export_build-demo-app {
  build_pipeline_parameters {
    items {
      default_value = "1.0.0"
      description   = ""
      name          = "APP_VERSION"
    }
    items {
      default_value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
      description   = ""
      name          = "DB_DSN"
    }
    items {
      default_value = "Oracle1234567"
      description   = ""
      name          = "DB_PASSWORD"
    }
    items {
      default_value = "admin"
      description   = ""
      name          = "DB_USER"
    }
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-19T08:47:15.806Z"
  }
  description  = ""
  display_name = "build-demo-app"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_DevOps-Demo.id
}

resource oci_devops_build_run export_build-demo-app-20250924-0845 {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-24T00:45:39.601Z"
  }
  display_name = "build-demo-app-20250924-0845"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_build-demo-app-20250924-0114 {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T17:14:45.876Z"
  }
  display_name = "build-demo-app-20250924-0114"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_build-demo-app-20250924-0051 {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T16:51:19.554Z"
  }
  display_name = "build-demo-app-20250924-0051"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_build-demo-app-20250923-2238 {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T14:38:51.012Z"
  }
  display_name = "build-demo-app-20250923-2238"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_ci-test-20250923-2225 {
  build_pipeline_id = "ocid1.devopsbuildpipeline.oc1.iad.amaaaaaaak7gbria66qe2k2xmxkoia375e4pbn6pm32pvps7txofe756feeq"
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T14:25:14.373Z"
  }
  display_name = "ci-test-20250923-2225"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_build-demo-app-20250923-2200 {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T14:01:53.394Z"
  }
  display_name = "build-demo-app-20250923-2200"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_ci-test-20250923-2156 {
  build_pipeline_id = "ocid1.devopsbuildpipeline.oc1.iad.amaaaaaaak7gbria66qe2k2xmxkoia375e4pbn6pm32pvps7txofe756feeq"
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T13:56:45.115Z"
  }
  display_name = "ci-test-20250923-2156"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_ci-test-20250923-2150 {
  build_pipeline_id = "ocid1.devopsbuildpipeline.oc1.iad.amaaaaaaak7gbria66qe2k2xmxkoia375e4pbn6pm32pvps7txofe756feeq"
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T13:50:22.382Z"
  }
  display_name = "ci-test-20250923-2150"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_ci-test-20250923-2141 {
  build_pipeline_id = "ocid1.devopsbuildpipeline.oc1.iad.amaaaaaaak7gbria66qe2k2xmxkoia375e4pbn6pm32pvps7txofe756feeq"
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T13:41:16.054Z"
  }
  display_name = "ci-test-20250923-2141"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_ci-test-20250923-2137 {
  build_pipeline_id = "ocid1.devopsbuildpipeline.oc1.iad.amaaaaaaak7gbria66qe2k2xmxkoia375e4pbn6pm32pvps7txofe756feeq"
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T13:37:55.368Z"
  }
  display_name = "ci-test-20250923-2137"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_ci-test-20250923-2132 {
  build_pipeline_id = "ocid1.devopsbuildpipeline.oc1.iad.amaaaaaaak7gbria66qe2k2xmxkoia375e4pbn6pm32pvps7txofe756feeq"
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T13:32:38.742Z"
  }
  display_name = "ci-test-20250923-2132"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_build-demo-app-20250923-2122 {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T13:22:38.295Z"
  }
  display_name = "build-demo-app-20250923-2122"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_build-demo-app-20250923-2109 {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T13:10:32.309Z"
  }
  display_name = "build-demo-app-20250923-2109"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_build-demo-app-20250923-2031 {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T12:31:23.913Z"
  }
  display_name = "build-demo-app-20250923-2031"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_build-demo-app-20250923-1953 {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T11:55:25.581Z"
  }
  display_name = "build-demo-app-20250923-1953"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_build-demo-app-20250923-1552 {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_run_arguments {
    items {
      name  = "APP_VERSION"
      value = "1.0.0"
    }
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T07:53:39.525Z"
  }
  display_name = "build-demo-app-20250923-1552"
  freeform_tags = {
  }
}

resource oci_devops_build_run export_build-demo-app-20250923-1422 {
  build_pipeline_id = oci_devops_build_pipeline.export_build-demo-app.id
  build_run_arguments {
    items {
      name  = "DB_DSN"
      value = "(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=kf4c11fo.adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=n7djxxqbnkflnvn_adbdemo_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    }
    items {
      name  = "DB_PASSWORD"
      value = "Oracle1234567"
    }
    items {
      name  = "DB_USER"
      value = "admin"
    }
  }
  commit_info {
    commit_hash       = ""
    repository_branch = ""
    repository_url    = ""
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-23T06:22:55.164Z"
  }
  display_name = "build-demo-app-20250923-1422"
  freeform_tags = {
  }
}

