## This configuration was generated by terraform-provider-oci

resource oci_logging_log_group export_devops_log_group {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-22T14:36:35.633Z"
  }
  #description = <<Optional value not found in discovery>>
  display_name = "devops_log_group"
  freeform_tags = {
  }
}

resource oci_logging_log export_DevOps_Demo_all {
  configuration {
    compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
    source {
      category = "all"
      parameters = {
      }
      resource    = oci_devops_project.export_DevOps-Demo.id
      service     = "devops"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-22T14:36:40.237Z"
  }
  display_name = "DevOps_Demo_all"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_devops_log_group.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

