## This configuration was generated by terraform-provider-oci

resource oci_ons_notification_topic export_Topic-Demo {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "default_tags.CreatedBy" = "oracleidentitycloudservice/wenbin.chen@oracle.com"
    "default_tags.CreatedOn" = "2025-09-19T08:41:57.075Z"
  }
  description = "Devops demo topic "
  freeform_tags = {
  }
  name = "Topic-Demo"
}

