# App Demo Manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  labels:
    app: app-demo
    version: <<APP_VERSION>>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
        version: <<APP_VERSION>>
    spec:
      containers:
      - name: app-demo
        image: iad.ocir.io/sehubjapacprod/wilbur/devops/app-demo-image:<<APP_VERSION>>
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          value: "<<DB_USER>>"
        - name: DB_PASSWORD
          value: "<<DB_PASSWORD>>"
        - name: DB_DSN
          value: "<<DB_DSN>>"
        - name: APP_VERSION
          value: "<<APP_VERSION>>"
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-service
  labels:
    app: app-demo
    version: <<APP_VERSION>>
spec:
  selector:
    app: app-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer